import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "./component/Container";
import Header from "./component/nav/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ubike 即時站點資訊",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
